const translations={
 en:{hero_title:'Simple guidance for government digital services',hero_subtitle:'Find, understand and use government digital portals through simple steps, document checklists and official links.',btn_search:'Search'},
 hi:{hero_title:'सरकारी डिजिटल सेवाओं के लिए सरल मार्गदर्शन',hero_subtitle:'सरल चरणों, दस्तावेज़ चेकलिस्ट और आधिकारिक लिंक के साथ सरकारी डिजिटल पोर्टल समझें और उपयोग करें।',btn_search:'खोजें'},
 mr:{hero_title:'शासकीय डिजिटल सेवांसाठी सोपे मार्गदर्शन',hero_subtitle:'सोप्या चरणांमध्ये, कागदपत्रांच्या चेकलिस्टसह आणि अधिकृत लिंकद्वारे शासकीय डिजिटल पोर्टल समजून घ्या.',btn_search:'शोधा'}
};
const guideData={
 pan:{title:'PAN Card',description:'Understand the application, required documents and next steps before continuing to the official PAN service portal.',portal:'https://www.incometaxindia.gov.in/tax-services/apply-for-pan',track:'https://www.incometaxindia.gov.in/en/pan',eligibility:'Check the current PAN eligibility and application category on the official Income Tax Department website before starting.',documents:['Proof of identity','Proof of address','Proof of date of birth','Active mobile number and email, where required','Scanned documents in the format and size accepted by the official portal'],steps:['Open the official PAN application page and choose the applicable online application option.','Select the correct applicant category and application type.','Enter your personal details exactly as shown on your supporting documents.','Keep the required identity, address and date-of-birth proofs ready and upload them when requested.','Complete the applicable fee/payment and verification process on the official portal.','Save the acknowledgement or application/reference number so you can track the request.']},
 aadhaar:{title:'Aadhaar Services',description:'Get simple guidance for common Aadhaar services while keeping the final action on the official UIDAI portal or authorised centre.',portal:'https://myaadhaar.uidai.gov.in/',track:'https://myaadhaar.uidai.gov.in/',eligibility:'The exact process depends on the Aadhaar service. Some updates may require a visit to an authorised Aadhaar centre.',documents:['Aadhaar number or enrolment details, when applicable','Registered mobile number for OTP-based services','Valid supporting proof for the requested update, when required','Original documents for centre-based services, when required'],steps:['Open the official UIDAI / myAadhaar website and select the service you need.','Read the eligibility and document requirements shown for that service.','Sign in or provide the requested Aadhaar details and OTP where applicable.','Upload supporting documents only through the official UIDAI process when online upload is available.','For services requiring an Aadhaar centre, use the official appointment or centre process.','Save the request or acknowledgement number for future reference.']},
 passport:{title:'Passport Seva',description:'Follow a simple preparation checklist for a fresh passport, reissue or related Passport Seva services.',portal:'https://www.passportindia.gov.in/',track:'https://www.passportindia.gov.in/',eligibility:'Requirements vary by fresh passport, reissue and other services. Confirm the current document list on Passport Seva.',documents:['Proof of present address','Proof of date of birth, when applicable','Existing passport for reissue, if applicable','Photographs or other documents only when the official process requires them','Original documents for the appointment'],steps:['Register or sign in on the official Passport Seva portal.','Choose the appropriate service such as fresh passport or reissue.','Complete the online application with accurate personal and address details.','Pay the applicable fee and schedule an appointment if required.','Prepare original documents and attend the designated appointment centre.','Use the official portal to check the application status.']},
 dl:{title:'Driving Licence Services',description:'Prepare for learner or driving licence services through the official Parivahan / Sarathi system.',portal:'https://parivahan.gov.in/',track:'https://parivahan.gov.in/',eligibility:'Age, learner licence, test and document requirements depend on the licence service and current rules for the applicant.',documents:['Proof of age','Proof of address','Passport-size photograph where required','Medical certificate where applicable','Existing licence or learner licence for applicable services'],steps:['Open the official Parivahan / Sarathi service and select the licence service.','Choose the appropriate state and service type.','Fill in the application details and upload documents when requested.','Pay the applicable fee and book a slot or test appointment when required.','Carry the required original documents to the designated centre.','Use the official portal to check the application or appointment status.']}
};
let currentFontSize=16;
function skipToMain(){document.getElementById('mainContent').focus({preventScroll:false});document.getElementById('mainContent').scrollIntoView({behavior:'smooth'});}
function toggleAccessibility(){document.getElementById('accessibilityPanel').classList.toggle('hidden');document.getElementById('accessChevron').classList.toggle('rotate');}
function changeFontSize(delta){currentFontSize=Math.min(22,Math.max(13,currentFontSize+delta));document.documentElement.style.fontSize=currentFontSize+'px';}
function resetFontSize(){currentFontSize=16;document.documentElement.style.fontSize='16px';}
function setSaturation(value){document.body.classList.remove('saturation-low','saturation-mid','saturation-high','saturation-max');if(value===.55)document.body.classList.add('saturation-low');else if(value===.8)document.body.classList.add('saturation-mid');else if(value===1.35)document.body.classList.add('saturation-high');else if(value===1.6)document.body.classList.add('saturation-max');}
let readerOn=false;
function toggleReader(){readerOn=!readerOn;document.getElementById('readerState').textContent=readerOn?'On':'Off';if(readerOn)speakText(document.querySelector('.page-view:not(.hidden)')?.innerText||'Citizen Assist');}
function speakText(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.slice(0,1800));u.rate=.95;window.speechSynthesis.speak(u);}
function toggleHighContrast(){document.body.classList.toggle('high-contrast');}
function toggleBasicView(){document.body.classList.toggle('basic-view');}
function toggleInvert(){document.body.classList.toggle('invert-mode');}
function resetAccessibility(){resetFontSize();setSaturation(1);document.body.classList.remove('high-contrast','basic-view','invert-mode');readerOn=false;document.getElementById('readerState').textContent='Off';}
function changeLanguage(lang){const t=translations[lang]||translations.en;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key])el.textContent=t[key];});document.documentElement.lang=lang;}
function updateNav(viewName){document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===viewName));}
function showView(viewName){document.querySelectorAll('.page-view').forEach(v=>v.classList.add('hidden'));const target=document.getElementById('view-'+viewName);if(target)target.classList.remove('hidden');updateNav(viewName);document.getElementById('navLinks').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(readerOn)speakText(target?.innerText||'');}
function toggleMobileMenu(){document.getElementById('navLinks').classList.toggle('open');}
function focusHomeSearch(){showView('home');setTimeout(()=>document.getElementById('homeSearchInput').focus(),150)}
function focusServiceSearch(){showView('services');setTimeout(()=>document.getElementById('serviceSearchInput').focus(),150)}
function executeHomeSearch(){const term=document.getElementById('homeSearchInput').value.trim();showView('services');document.getElementById('serviceSearchInput').value=term;filterServicesList();}
function filterByRole(role){showView('services');const input=document.getElementById('serviceSearchInput');input.value=role==='all'?'':role;filterServicesList();}
function filterServicesList(){const query=document.getElementById('serviceSearchInput').value.toLowerCase().trim();const cat=document.getElementById('filterCategory').value;const diff=document.getElementById('filterDifficulty').value;let visible=0;document.querySelectorAll('.service-entry').forEach(entry=>{const matchQ=entry.dataset.keywords.includes(query);const matchC=cat==='all'||entry.dataset.category===cat;const matchD=diff==='all'||entry.dataset.difficulty===diff;const ok=matchQ&&matchC&&matchD;entry.style.display=ok?'flex':'none';if(ok)visible++;});document.getElementById('noServices').classList.toggle('hidden',visible!==0);}
function openGuide(key){const d=guideData[key];if(!d)return;document.getElementById('guideTitle').textContent=d.title;document.getElementById('guideDescription').textContent=d.description;document.getElementById('guideEligibility').textContent=d.eligibility;document.getElementById('officialPortalBtn').href=d.portal;document.getElementById('applyNowBtn').href=d.portal;document.getElementById('trackPortalBtn').href=d.track;document.getElementById('documentsContainer').innerHTML=d.documents.map(x=>`<li><i class="fa-solid fa-circle-check"></i><span>${x}</span></li>`).join('');renderChecklist(d.steps);showView('guide');}
function scrollToGuideSection(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});}
function toggleFaq(btn){const answer=btn.nextElementSibling;const icon=btn.querySelector('i');answer.classList.toggle('hidden');icon.classList.toggle('fa-chevron-up');icon.classList.toggle('fa-chevron-down');}
function filterFaq(){const q=document.getElementById('faqSearchInput').value.toLowerCase();document.querySelectorAll('.faq-item').forEach(item=>item.style.display=item.innerText.toLowerCase().includes(q)?'block':'none');}
function handleContactSubmit(e){e.preventDefault();alert('Thank you! Your feedback has been received.');e.target.reset();showView('home');}
document.addEventListener('DOMContentLoaded',()=>{showView('home');});
